### ISSUE TITLE
Hi 有源数据吗？

### ISSUE THREAD

**Issue by tomant1024** [XBaith/ams-recommend-system#3]

**Comment by tomant1024** [comment]
真实的数据

**Comment by xxubai** [comment]
> 真实的数据

目前没有找到有关文章网站的真实数据源，本系统是以练习为主，仅通过shell脚本生成的数据。不过有[Moive Lens](https://grouplens.org/datasets/movielens/)的数据是真实的，可以根据自己需要改写成电影推荐。
